# Generated by Django 3.2.3 on 2021-05-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('num_celular', models.IntegerField()),
                ('num_fijo', models.IntegerField()),
                ('codigo_postal', models.IntegerField()),
                ('colonia', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('rfc', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
