# Generated by Django 3.2.3 on 2021-05-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='num_celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='num_fijo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
