# Generated by Django 3.2.3 on 2021-05-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20210519_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_ingreso',
            new_name='fecha_registro',
        ),
    ]
