# Generated by Django 3.2.3 on 2021-05-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_poliza', models.CharField(max_length=30)),
                ('deducible', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('tipo_poliza', models.CharField(max_length=30)),
                ('periodo_pago', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
        ),
    ]
