# Generated by Django 3.2.3 on 2021-05-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_poliza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.ForeignKey(default='Activo', on_delete=django.db.models.deletion.CASCADE, to='Clientes.status'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='status',
            field=models.ForeignKey(default='Activo', on_delete=django.db.models.deletion.CASCADE, to='Clientes.status'),
        ),
    ]
