# Generated by Django 3.2.3 on 2021-05-27 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_auto_20210527_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Clientes.status'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Clientes.status'),
        ),
    ]
