# Generated by Django 3.2.3 on 2021-05-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_auto_20210527_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodos_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='poliza',
            name='periodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.periodos_pago'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='tipo_poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipos_poliza'),
        ),
    ]
