# Generated by Django 3.2.3 on 2021-06-08 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0014_auto_20210527_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_prima', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateField()),
                ('prima_neta', models.CharField(max_length=30)),
                ('comision_agente', models.CharField(max_length=30)),
                ('total_pagar', models.CharField(max_length=30)),
                ('ruta_comprobante', models.CharField(default='Hola', max_length=30)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.poliza')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.status')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipos_pago')),
            ],
        ),
    ]
