# Generated by Django 3.2.3 on 2021-06-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0015_prima_tipospago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prima',
            name='tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipospago'),
        ),
    ]
