# Generated by Django 3.2.3 on 2021-05-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0004_auto_20210524_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
