# Generated by Django 3.2.3 on 2021-05-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0006_alter_agente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='fecha_nacimiento',
        ),
    ]
