# Generated by Django 3.2.3 on 2021-05-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agentes', '0007_remove_agente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='colonia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
